# Redirect HTTP to HTTPS for shubnit.com and www.shubnit.com
server {
    listen 80;
    server_name shubnit.com www.shubnit.com;

    return 301 https://www.shubnit.com$request_uri;
}

server {
    listen 443 ssl;
    server_name shubnit.com www.shubnit.com;

    ssl_certificate /etc/letsencrypt/live/shubnit.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shubnit.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /home/ubuntu/portfolio/www/public;
    index pp.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
