name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: generate tag
        id: tag
        run: echo "TAG=v$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: create ZIP of static files
        run: zip -r portfolio.zip images/ public/ ec2-setup/ -x "*.git*"


      - name: Create Github Release and upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          name: Release ${{ steps.tag.outputs.TAG }}
          files: portfolio.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
